from __future__ import annotations

import re
import secrets
import subprocess
from pathlib import Path
from typing import Any

import yaml

from app.config import get_config

MARKER_FILTERS_BEGIN = "# MAILPANEL_FILTERS_BEGIN"
MARKER_FILTERS_END = "# MAILPANEL_FILTERS_END"
MARKER_SA_RULES_BEGIN = "# MAILPANEL_SA_FILTERS_BEGIN"
MARKER_SA_RULES_END = "# MAILPANEL_SA_FILTERS_END"

FILTER_SCORE = 100.0
VALID_FIELDS = {"subject", "body"}
FIELD_LABELS = {"subject": "Тема", "body": "Текст"}
RULE_ID_RE = re.compile(r"^[a-z0-9]{6,16}$")


class ContentFilterError(RuntimeError):
    pass


def _project_root() -> Path:
    return Path(__file__).resolve().parents[2]


def content_filters_path() -> Path:
    default = _project_root() / "data" / "content_filters.yaml"
    return Path(getattr(get_config().paths, "content_filters_file", str(default)))


def spamassassin_filters_path() -> Path:
    default = Path("/etc/mail/spamassassin/mailpanel_filters.cf")
    configured = getattr(get_config().paths, "spamassassin_filters_file", None)
    return Path(configured) if configured else default


def spamassassin_config_path() -> Path:
    configured = Path(get_config().paths.spamassassin_config)
    if configured.is_file():
        return configured
    for candidate in (
        configured,
        Path("/etc/mail/spamassassin/local.cf"),
        Path("/etc/spamassassin/local.cf"),
    ):
        if candidate.is_file():
            return candidate
    return configured


def _validate_pattern(pattern: str) -> str:
    text = pattern.strip()
    if not text:
        raise ValueError("Укажите текст для поиска")
    if len(text) > 200:
        raise ValueError("Текст поиска не длиннее 200 символов")
    if "\n" in text or "\r" in text:
        raise ValueError("Текст поиска не должен содержать переносы строк")
    return text


def _validate_field(field: str) -> str:
    value = field.strip().lower()
    if value not in VALID_FIELDS:
        raise ValueError("Поле должно быть subject или body")
    return value


def _validate_rule_id(rule_id: str) -> str:
    rule_id = rule_id.strip().lower()
    if not RULE_ID_RE.fullmatch(rule_id):
        raise ValueError("Некорректный идентификатор правила")
    return rule_id


def _read_filters_file() -> list[dict[str, Any]]:
    path = content_filters_path()
    if not path.exists():
        return []
    data = yaml.safe_load(path.read_text(encoding="utf-8", errors="replace")) or {}
    filters = data.get("filters") or []
    if not isinstance(filters, list):
        return []
    return [item for item in filters if isinstance(item, dict)]


def _write_filters_file(filters: list[dict[str, Any]]) -> None:
    path = content_filters_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        yaml.safe_dump({"filters": filters}, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


def _normalize_filter(raw: dict[str, Any]) -> dict[str, Any]:
    rule_id = _validate_rule_id(str(raw.get("id", "")))
    field = _validate_field(str(raw.get("field", "")))
    pattern = _validate_pattern(str(raw.get("pattern", "")))
    enabled = bool(raw.get("enabled", True))
    return {
        "id": rule_id,
        "field": field,
        "field_label": FIELD_LABELS[field],
        "pattern": pattern,
        "action": "quarantine",
        "action_label": "Карантин",
        "enabled": enabled,
    }


def _rule_name(rule: dict[str, Any]) -> str:
    prefix = "SUBJ" if rule["field"] == "subject" else "BODY"
    return f"MAILPANEL_{prefix}_{rule['id'].upper()}"


def _sa_regex(pattern: str) -> str:
    return re.escape(pattern)


def _enabled_rules(filters: list[dict[str, Any]]) -> list[dict[str, Any]]:
    enabled: list[dict[str, Any]] = []
    for item in filters:
        if not item.get("enabled"):
            continue
        enabled.append(
            {
                "id": str(item.get("id", "")),
                "field": str(item.get("field", "")),
                "pattern": str(item.get("pattern", "")),
                "enabled": True,
            }
        )
    return enabled


def _build_spamassassin_rule_lines(filters: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    for rule in _enabled_rules(filters):
        normalized = _normalize_filter(rule)
        name = _rule_name(normalized)
        regex = _sa_regex(normalized["pattern"])
        if normalized["field"] == "subject":
            lines.append(f"header {name} Subject =~ /{regex}/i")
        else:
            lines.append(f"body {name} /{regex}/i")
        lines.append(f"score {name} {FILTER_SCORE:g}")
        lines.append(f"describe {name} MailPanel content filter ({normalized['field']})")
        lines.append("")
    return lines


def _build_spamassassin_rules(filters: list[dict[str, Any]]) -> str:
    lines = [
        "# Generated by MailPanel. Do not edit manually.",
        MARKER_FILTERS_BEGIN,
        "# Incoming content filters: high score -> spam quarantine in Amavis.",
    ]
    rule_lines = _build_spamassassin_rule_lines(filters)
    if rule_lines:
        lines.extend(rule_lines)
    else:
        lines.append("# No active rules.")
    lines.append(MARKER_FILTERS_END)
    return "\n".join(lines).rstrip() + "\n"


def _ensure_local_cf_rules_block(content: str, filters: list[dict[str, Any]]) -> str:
    rule_lines = _build_spamassassin_rule_lines(filters)
    if rule_lines:
        inner = "\n".join(rule_lines).rstrip()
    else:
        inner = "# No active MailPanel content filter rules."
    block = f"{MARKER_SA_RULES_BEGIN}\n{inner}\n{MARKER_SA_RULES_END}"
    marker_pattern = (
        re.escape(MARKER_SA_RULES_BEGIN) + r".*?" + re.escape(MARKER_SA_RULES_END)
    )
    if re.search(marker_pattern, content, flags=re.DOTALL):
        return re.sub(marker_pattern, block, content, count=1, flags=re.DOTALL)
    # Remove legacy include-only block if present.
    legacy_include = (
        re.escape(MARKER_SA_RULES_BEGIN)
        + r"\ninclude .*?\n"
        + re.escape(MARKER_SA_RULES_END)
    )
    content = re.sub(legacy_include, block, content, count=1, flags=re.DOTALL)
    if MARKER_SA_RULES_BEGIN in content:
        return re.sub(marker_pattern, block, content, count=1, flags=re.DOTALL)
    return content.rstrip() + "\n\n" + block + "\n"


def _ensure_required_score(content: str) -> str:
    if re.search(r"^required_score\s+", content, flags=re.MULTILINE):
        return content
    return content.rstrip() + "\n\nrequired_score 5.0\n"


def _restart_amavisd() -> None:
    subprocess.run(["systemctl", "restart", "amavisd"], check=False)


def _run_spamassassin_lint(local_cf: Path) -> str | None:
    result = subprocess.run(
        ["spamassassin", "--lint", "-C", str(local_cf.parent)],
        capture_output=True,
        text=True,
        check=False,
        timeout=60,
    )
    if result.returncode == 0:
        return None
    return (result.stderr or result.stdout or "spamassassin --lint failed").strip()


def _sync_amavis_policy(filters: list[dict[str, Any]]) -> list[str]:
    warnings: list[str] = []
    if not _enabled_rules(filters):
        return warnings
    try:
        from app.services import amavis_policy

        policy = amavis_policy.read_mail_policy()
        if not policy.get("scan_internal_mail"):
            amavis_policy.write_mail_policy(True)
            warnings.append(
                "Автоматически включена проверка внутренней почты в Amavis "
                "(нужна для правил между ящиками на этом сервере)."
            )
    except Exception as exc:
        warnings.append(f"Не удалось обновить политику Amavis: {exc}")
    return warnings


def _diagnostics(filters: list[dict[str, Any]]) -> dict[str, Any]:
    local_cf = spamassassin_config_path()
    content = local_cf.read_text(encoding="utf-8", errors="replace") if local_cf.is_file() else ""
    rules_in_local_cf = "header MAILPANEL_" in content or "body MAILPANEL_" in content
    scan_internal_mail = False
    try:
        from app.services import amavis_policy

        scan_internal_mail = bool(amavis_policy.read_mail_policy().get("scan_internal_mail"))
    except Exception:
        scan_internal_mail = False
    return {
        "local_cf": str(local_cf),
        "local_cf_exists": local_cf.is_file(),
        "rules_in_local_cf": rules_in_local_cf,
        "active_rules": len(_enabled_rules(filters)),
        "scan_internal_mail": scan_internal_mail,
    }


def _apply_filters(filters: list[dict[str, Any]]) -> list[str]:
    warnings: list[str] = []
    filters_path = spamassassin_filters_path()
    filters_path.parent.mkdir(parents=True, exist_ok=True)
    filters_path.write_text(_build_spamassassin_rules(filters), encoding="utf-8")

    local_cf = spamassassin_config_path()
    if not local_cf.is_file():
        raise ContentFilterError(
            f"Файл SpamAssassin local.cf не найден: {local_cf}. "
            "Проверьте paths.spamassassin_config в config.yaml"
        )
    try:
        content = local_cf.read_text(encoding="utf-8", errors="replace")
        content = _ensure_required_score(content)
        content = _ensure_local_cf_rules_block(content, filters)
        local_cf.write_text(content, encoding="utf-8")
    except OSError as exc:
        raise ContentFilterError(f"Не удалось обновить {local_cf}: {exc}") from exc

    lint_error = _run_spamassassin_lint(local_cf)
    if lint_error:
        warnings.append(f"Проверка spamassassin --lint: {lint_error[:300]}")

    warnings.extend(_sync_amavis_policy(filters))
    _restart_amavisd()
    return warnings


def list_content_filters() -> dict[str, Any]:
    raw_filters = _read_filters_file()
    filters = [_normalize_filter(item) for item in raw_filters]
    diagnostics = _diagnostics(raw_filters)
    notes = [
        "Правила проверяют почту через SpamAssassin внутри Amavis.",
        "При совпадении письмо получает высокий spam score и попадает в карантин (тип «Спам»).",
        "Поиск без учёта регистра, по вхождению указанного текста.",
        "Письма между ящиками на этом сервере требуют включённой проверки внутренней почты.",
        "Отправители из белого списка могут обходить проверку SpamAssassin.",
    ]
    if diagnostics["active_rules"] and not diagnostics["scan_internal_mail"]:
        notes.insert(
            4,
            "Сейчас внутренняя почта не проверяется — пересохраните правило или включите "
            "«Проверять внутреннюю почту» в разделе Антиспам.",
        )
    return {
        "items": filters,
        "total": len(filters),
        "source_file": str(content_filters_path()),
        "rules_file": str(spamassassin_filters_path()),
        "diagnostics": diagnostics,
        "notes": notes,
    }


def create_content_filter(field: str, pattern: str, enabled: bool = True) -> dict[str, Any]:
    filters = _read_filters_file()
    rule = _normalize_filter(
        {
            "id": secrets.token_hex(4),
            "field": field,
            "pattern": pattern,
            "enabled": enabled,
        }
    )
    filters.append(
        {
            "id": rule["id"],
            "field": rule["field"],
            "pattern": rule["pattern"],
            "enabled": rule["enabled"],
        }
    )
    _write_filters_file(filters)
    try:
        warnings = _apply_filters(filters)
    except Exception as exc:
        raise ContentFilterError(str(exc)) from exc
    if warnings:
        rule["warnings"] = warnings
    return rule


def update_content_filter(
    rule_id: str,
    *,
    field: str | None = None,
    pattern: str | None = None,
    enabled: bool | None = None,
) -> dict[str, Any]:
    rule_id = _validate_rule_id(rule_id)
    filters = _read_filters_file()
    index = next((idx for idx, item in enumerate(filters) if str(item.get("id")) == rule_id), None)
    if index is None:
        raise ValueError(f"Правило не найдено: {rule_id}")

    current = dict(filters[index])
    if field is not None:
        current["field"] = _validate_field(field)
    if pattern is not None:
        current["pattern"] = _validate_pattern(pattern)
    if enabled is not None:
        current["enabled"] = bool(enabled)

    rule = _normalize_filter(current)
    filters[index] = {
        "id": rule["id"],
        "field": rule["field"],
        "pattern": rule["pattern"],
        "enabled": rule["enabled"],
    }
    _write_filters_file(filters)
    try:
        warnings = _apply_filters(filters)
    except Exception as exc:
        raise ContentFilterError(str(exc)) from exc
    if warnings:
        rule["warnings"] = warnings
    return rule


def delete_content_filter(rule_id: str) -> None:
    rule_id = _validate_rule_id(rule_id)
    filters = _read_filters_file()
    next_filters = [item for item in filters if str(item.get("id")) != rule_id]
    if len(next_filters) == len(filters):
        raise ValueError(f"Правило не найдено: {rule_id}")
    _write_filters_file(next_filters)
    try:
        _apply_filters(next_filters)
    except Exception as exc:
        raise ContentFilterError(str(exc)) from exc


def reapply_content_filters() -> dict[str, Any]:
    filters = _read_filters_file()
    warnings = _apply_filters(filters)
    return {"ok": True, "warnings": warnings, "diagnostics": _diagnostics(filters)}
