"""Generated Amavis custom package for MailPanel content filters."""

from __future__ import annotations


def build_package(rules_block: str, cyrillic_from: str, cyrillic_to: str) -> str:
    return f"""# Generated by MailPanel. Do not edit manually.
# Replaces placeholder routines in Amavis::Custom and registers a spam scanner.
use utf8;
use strict;
use warnings;
no warnings qw(redefine uninitialized);

package MailPanel::Filters;

our @RULES = (
{rules_block}
);

sub _fold_text {{
  my ($text) = @_;
  return '' unless defined $text;
  $text = lc($text);
  $text =~ tr/{cyrillic_from}/{cyrillic_to}/;
  return $text;
}}

sub _decode_header {{
  my ($value) = @_;
  return '' unless defined $value;
  local $1;
  $value =~ s/\\n([ \\t])/$1/sg;
  $value =~ s/^[ \\t]+//s;
  $value =~ s/[ \\t]+\\z//s;
  my $raw = $value;
  eval {{
    require MIME::Words;
    my $decoded = MIME::Words::decode_mime_words($raw);
    $value = $decoded if defined $decoded && length $decoded;
  }};
  return $value;
}}

sub _subject_from_mail_file {{
  my ($msginfo) = @_;
  my @values;
  my $fn = $msginfo->mail_text_fn;
  return @values unless $fn && -f $fn;
  open my $fh, '<', $fn or return @values;
  binmode($fh, ':raw');
  while (my $line = <$fh>) {{
    last if $line =~ /^\\r?$/;
    if ($line =~ /^Subject:\\s*(.*)/i) {{
      my $val = $1;
      $val =~ s/\\r?\\n$//;
      push @values, $val if defined $val && length $val;
      my $decoded = _decode_header($val);
      push @values, $decoded if length $decoded;
    }}
  }}
  close $fh;
  return @values;
}}

sub _from_from_mail_file {{
  my ($msginfo) = @_;
  my @values;
  my $fn = $msginfo->mail_text_fn;
  return @values unless $fn && -f $fn;
  open my $fh, '<', $fn or return @values;
  binmode($fh, ':raw');
  while (my $line = <$fh>) {{
    last if $line =~ /^\\r?$/;
    if ($line =~ /^(?:From|Sender|Reply-To):\\s*(.*)/i) {{
      my $val = $1;
      $val =~ s/\\r?\\n$//;
      push @values, $val if defined $val && length $val;
      my $decoded = _decode_header($val);
      push @values, $decoded if length $decoded;
    }}
  }}
  close $fh;
  return @values;
}}

sub _match_literals {{
  my ($values, $literals) = @_;
  return 0 unless $values && $literals && @$literals;
  for my $literal (@$literals) {{
    next unless defined $literal && length $literal;
    for my $value (@$values) {{
      next unless defined $value && length $value;
      my $decoded = _decode_header($value);
      for my $candidate ($value, $decoded) {{
        next unless defined $candidate && length $candidate;
        return 1 if index($candidate, $literal) >= 0;
        return 1 if index(_fold_text($candidate), _fold_text($literal)) >= 0;
      }}
    }}
  }}
  return 0;
}}

sub _subject_candidates {{
  my ($msginfo) = @_;
  my @values;
  my $raw = $msginfo->get_header_field_body('subject');
  push @values, $raw if defined $raw && length $raw;
  for my $line ($msginfo->get_header_field('Subject')) {{
    next unless defined $line && length $line;
    push @values, $line;
    my $decoded = _decode_header($line);
    push @values, $decoded if length $decoded;
  }}
  if (defined $raw) {{
    my $decoded = _decode_header($raw);
    push @values, $decoded if length $decoded;
  }}
  push @values, _subject_from_mail_file($msginfo);
  my %seen;
  return grep {{ defined $_ && length $_ && !$seen{{_fold_text($_)}}++ }} @values;
}}

sub _from_candidates {{
  my ($msginfo) = @_;
  my @values;
  my $raw = $msginfo->get_header_field_body('from');
  push @values, $raw if defined $raw && length $raw;
  for my $hdr (qw(From Sender Reply-To)) {{
    for my $line ($msginfo->get_header_field($hdr)) {{
      next unless defined $line && length $line;
      push @values, $line;
      my $decoded = _decode_header($line);
      push @values, $decoded if length $decoded;
    }}
  }}
  if (defined $raw) {{
    my $decoded = _decode_header($raw);
    push @values, $decoded if length $decoded;
  }}
  my $envelope = $msginfo->sender;
  push @values, $envelope if defined $envelope && length $envelope;
  push @values, _from_from_mail_file($msginfo);
  my %seen;
  return grep {{ defined $_ && length $_ && !$seen{{_fold_text($_)}}++ }} @values;
}}

sub _match_patterns {{
  my ($values, $patterns, $field_name) = @_;
  $field_name = 'subject' unless defined $field_name && length $field_name;
  return ('', 0) unless $values && @$patterns;
  for my $value (@$values) {{
    my @candidates = ($value);
    if ($field_name eq 'subject' || $field_name eq 'from') {{
      my $decoded = _decode_header($value);
      push @candidates, $decoded if length $decoded;
    }}
    for my $candidate (@candidates) {{
      for my $pat (@$patterns) {{
        return ($field_name, 1) if $candidate =~ $pat;
      }}
    }}
  }}
  return ('', 0);
}}

sub _read_body_sample {{
  my ($msginfo) = @_;
  my $fn = $msginfo->mail_text_fn;
  return '' unless $fn && -f $fn;
  open my $fh, '<', $fn or return '';
  binmode($fh, ':raw');
  my $in_headers = 1;
  my $body = '';
  while (my $line = <$fh>) {{
    if ($in_headers) {{
      $in_headers = 0 if $line =~ /^\\r?$/;
      next;
    }}
    $body .= $line;
    last if length($body) > 131072;
  }}
  close $fh;
  return $body;
}}

sub match_mail {{
  my ($msginfo) = @_;
  my @subjects;
  my @froms;
  my $body;
  my $have_subjects = 0;
  my $have_froms = 0;
  my $have_body = 0;
  for my $rule (@RULES) {{
    my $field = $rule->{{field}} || '';
    my @values;
    if ($field eq 'subject') {{
      unless ($have_subjects) {{
        @subjects = _subject_candidates($msginfo);
        $have_subjects = 1;
      }}
      @values = @subjects;
    }} elsif ($field eq 'from') {{
      unless ($have_froms) {{
        @froms = _from_candidates($msginfo);
        $have_froms = 1;
      }}
      @values = @froms;
    }} else {{
      unless ($have_body) {{
        $body = _read_body_sample($msginfo);
        $have_body = 1;
      }}
      @values = ($body);
    }}
    my $literals = $rule->{{literals}} || [];
    if (@$literals && _match_literals(\\@values, $literals)) {{
      return ($field, 1, $rule->{{action}} || 'quarantine', $rule->{{forward_to}} || '', $rule->{{id}} || '');
    }}
    my $patterns = $rule->{{patterns}} || [];
    if (@$patterns) {{
      my ($matched_field, $matched) = _match_patterns(\\@values, $patterns, $field);
      if ($matched) {{
        return ($matched_field, 1, $rule->{{action}} || 'quarantine', $rule->{{forward_to}} || '', $rule->{{id}} || '');
      }}
    }}
  }}
  return ('', 0, '', '', '');
}}

package main;

sub Amavis::Custom::new {{
  my ($class, $conn, $msginfo) = @_;
  Amavis::Util::do_log(0, "MAILPANEL: custom new() <%s>", $msginfo->sender || '?');
  bless {{
    mailpanel_done => 0,
    mailpanel_match => '',
    mailpanel_action => '',
    mailpanel_forward_to => '',
    mailpanel_rule_id => '',
  }}, $class;
}}

sub Amavis::Custom::checks {{
  my ($self, $conn, $msginfo) = @_;
  my ($field, $matched, $action, $forward_to, $rule_id) = MailPanel::Filters::match_mail($msginfo);
  return unless $matched;
  $self->{{mailpanel_match}} = $field;
  $self->{{mailpanel_action}} = $action || 'quarantine';
  $self->{{mailpanel_forward_to}} = $forward_to || '';
  $self->{{mailpanel_rule_id}} = $rule_id || '';
  if (($action || '') eq 'quarantine') {{
    Amavis::load_policy_bank('MAILPANEL_CONTENT');
    for my $r (@{{$msginfo->per_recip_data}}) {{
      $r->bypass_spam_checks(0);
      my $rl = $r->spam_level;
      $rl = 0 if !defined $rl || $rl eq '';
      $r->spam_level($rl + 100);
    }}
  }}
  Amavis::Util::do_log(0, "MAILPANEL: checks matched (%s/%s) <%s>",
    $field, $action || '?', $msginfo->sender || '?');
}}

sub Amavis::Custom::before_send {{
  my ($self, $conn, $msginfo) = @_;
  return if $self->{{mailpanel_done}};
  my $field = $self->{{mailpanel_match}};
  my $action = $self->{{mailpanel_action}};
  my $forward_to = $self->{{mailpanel_forward_to}} || '';
  unless ($field && $action) {{
    my ($f, $matched, $act, $fwd, $rid) = MailPanel::Filters::match_mail($msginfo);
    return unless $matched;
    $field = $f;
    $action = $act || 'quarantine';
    $forward_to = $fwd || '';
    $self->{{mailpanel_rule_id}} = $rid || '';
  }}
  if ($action eq 'delete') {{
    for my $r (@{{$msginfo->per_recip_data}}) {{
      $r->recip_destiny(-1);
      $r->recip_smtp_response('250 2.7.0 MailPanel content filter discard');
      $r->recip_done(1);
    }}
    $self->{{mailpanel_done}} = 1;
    Amavis::Util::do_log(0, "MAILPANEL: before_send delete (%s)", $field);
    return;
  }}
  if ($action eq 'forward') {{
    if (!defined $forward_to || !length $forward_to) {{
      Amavis::Util::do_log(0, "MAILPANEL: before_send forward missing address (%s)", $field);
      return;
    }}
    for my $r (@{{$msginfo->per_recip_data}}) {{
      my $curr = eval {{ $r->recip_addr }} || '';
      next if defined $curr && length $curr && lc($curr) eq lc($forward_to);
      eval {{ $r->recip_addr_modified($forward_to); 1 }}
        or Amavis::Util::do_log(0, "MAILPANEL: recip_addr_modified failed: %s", $@);
    }}
    $self->{{mailpanel_done}} = 1;
    Amavis::Util::do_log(0, "MAILPANEL: before_send forward (%s) -> %s", $field, $forward_to);
    return;
  }}
  my $method = $main::spam_quarantine_method;
  $method = 'sql:spam-%m' unless defined $method && length $method;
  my $quar_to = $main::spam_quarantine_to;
  $quar_to = 'spam-quarantine@localhost' unless defined $quar_to && length $quar_to;
  eval {{ my $he = $msginfo->header_edits; }};
  my $quar_ok = 0;
  eval {{
    Amavis::do_quarantine($conn, $msginfo, undef, [$quar_to], $method);
    $quar_ok = 1;
  }};
  if ($quar_ok) {{
    for my $r (@{{$msginfo->per_recip_data}}) {{
      $r->recip_destiny(0);
      $r->recip_smtp_response('250 2.7.0 MailPanel content filter quarantine');
      $r->recip_done(1);
    }}
    $self->{{mailpanel_done}} = 1;
    Amavis::Util::do_log(0, "MAILPANEL: before_send quarantine (%s)", $field);
  }} else {{
    Amavis::Util::do_log(0, "MAILPANEL: before_send quarantine failed (%s): %s", $field, $@);
  }}
}}

1;

warn sprintf("MAILPANEL: loaded %d content filter rules\\n", scalar(@MailPanel::Filters::RULES));
"""
