from __future__ import annotations

import re
import secrets
import subprocess
from pathlib import Path
from typing import Any

import yaml

from app.config import get_config

MARKER_FILTERS_BEGIN = "# MAILPANEL_FILTERS_BEGIN"
MARKER_FILTERS_END = "# MAILPANEL_FILTERS_END"
MARKER_SA_INCLUDE_BEGIN = "# MAILPANEL_SA_FILTERS_BEGIN"
MARKER_SA_INCLUDE_END = "# MAILPANEL_SA_FILTERS_END"

FILTER_SCORE = 100.0
VALID_FIELDS = {"subject", "body"}
FIELD_LABELS = {"subject": "Тема", "body": "Текст"}
RULE_ID_RE = re.compile(r"^[a-z0-9]{6,16}$")


class ContentFilterError(RuntimeError):
    pass


def _project_root() -> Path:
    return Path(__file__).resolve().parents[2]


def content_filters_path() -> Path:
    default = _project_root() / "data" / "content_filters.yaml"
    return Path(getattr(get_config().paths, "content_filters_file", str(default)))


def spamassassin_filters_path() -> Path:
    default = Path("/etc/mail/spamassassin/mailpanel_filters.cf")
    configured = getattr(get_config().paths, "spamassassin_filters_file", None)
    return Path(configured) if configured else default


def spamassassin_config_path() -> Path:
    configured = Path(get_config().paths.spamassassin_config)
    if configured.is_file():
        return configured
    for candidate in (
        configured,
        Path("/etc/mail/spamassassin/local.cf"),
        Path("/etc/spamassassin/local.cf"),
    ):
        if candidate.is_file():
            return candidate
    return configured


def _validate_pattern(pattern: str) -> str:
    text = pattern.strip()
    if not text:
        raise ValueError("Укажите текст для поиска")
    if len(text) > 200:
        raise ValueError("Текст поиска не длиннее 200 символов")
    if "\n" in text or "\r" in text:
        raise ValueError("Текст поиска не должен содержать переносы строк")
    return text


def _validate_field(field: str) -> str:
    value = field.strip().lower()
    if value not in VALID_FIELDS:
        raise ValueError("Поле должно быть subject или body")
    return value


def _validate_rule_id(rule_id: str) -> str:
    rule_id = rule_id.strip().lower()
    if not RULE_ID_RE.fullmatch(rule_id):
        raise ValueError("Некорректный идентификатор правила")
    return rule_id


def _read_filters_file() -> list[dict[str, Any]]:
    path = content_filters_path()
    if not path.exists():
        return []
    data = yaml.safe_load(path.read_text(encoding="utf-8", errors="replace")) or {}
    filters = data.get("filters") or []
    if not isinstance(filters, list):
        return []
    return [item for item in filters if isinstance(item, dict)]


def _write_filters_file(filters: list[dict[str, Any]]) -> None:
    path = content_filters_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        yaml.safe_dump({"filters": filters}, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )


def _normalize_filter(raw: dict[str, Any]) -> dict[str, Any]:
    rule_id = _validate_rule_id(str(raw.get("id", "")))
    field = _validate_field(str(raw.get("field", "")))
    pattern = _validate_pattern(str(raw.get("pattern", "")))
    enabled = bool(raw.get("enabled", True))
    return {
        "id": rule_id,
        "field": field,
        "field_label": FIELD_LABELS[field],
        "pattern": pattern,
        "action": "quarantine",
        "action_label": "Карантин",
        "enabled": enabled,
    }


def _rule_name(rule: dict[str, Any]) -> str:
    prefix = "SUBJ" if rule["field"] == "subject" else "BODY"
    return f"MAILPANEL_{prefix}_{rule['id'].upper()}"


def _sa_regex(pattern: str) -> str:
    return re.escape(pattern)


def _build_spamassassin_rules(filters: list[dict[str, Any]]) -> str:
    lines = [
        "# Generated by MailPanel. Do not edit manually.",
        MARKER_FILTERS_BEGIN,
        "# Incoming content filters: high score -> spam quarantine in Amavis.",
    ]
    enabled = [rule for rule in filters if rule.get("enabled")]
    if not enabled:
        lines.append("# No active rules.")
    for rule in enabled:
        name = _rule_name(rule)
        regex = _sa_regex(rule["pattern"])
        if rule["field"] == "subject":
            lines.append(f"header {name} Subject =~ /{regex}/i")
        else:
            lines.append(f"body {name} /{regex}/i")
        lines.append(f"score {name} {FILTER_SCORE:g}")
        lines.append("")
    lines.append(MARKER_FILTERS_END)
    return "\n".join(lines).rstrip() + "\n"


def _ensure_local_cf_include(content: str, filters_file: Path) -> str:
    include_line = f"include {filters_file.as_posix()}"
    block = (
        f"{MARKER_SA_INCLUDE_BEGIN}\n"
        f"{include_line}\n"
        f"{MARKER_SA_INCLUDE_END}"
    )
    marker_pattern = (
        re.escape(MARKER_SA_INCLUDE_BEGIN)
        + r".*?"
        + re.escape(MARKER_SA_INCLUDE_END)
    )
    if re.search(marker_pattern, content, flags=re.DOTALL):
        return re.sub(marker_pattern, block, content, count=1, flags=re.DOTALL)
    return content.rstrip() + "\n\n" + block + "\n"


def _restart_amavisd() -> None:
    subprocess.run(["systemctl", "restart", "amavisd"], check=False)


def _apply_filters(filters: list[dict[str, Any]]) -> None:
    filters_path = spamassassin_filters_path()
    filters_path.parent.mkdir(parents=True, exist_ok=True)
    filters_path.write_text(_build_spamassassin_rules(filters), encoding="utf-8")

    local_cf = spamassassin_config_path()
    if not local_cf.is_file():
        raise ContentFilterError(
            f"Файл SpamAssassin local.cf не найден: {local_cf}. "
            "Проверьте paths.spamassassin_config в config.yaml"
        )
    try:
        content = local_cf.read_text(encoding="utf-8", errors="replace")
        content = _ensure_local_cf_include(content, filters_path)
        local_cf.write_text(content, encoding="utf-8")
    except OSError as exc:
        raise ContentFilterError(f"Не удалось обновить {local_cf}: {exc}") from exc
    _restart_amavisd()


def list_content_filters() -> dict[str, Any]:
    filters = [_normalize_filter(item) for item in _read_filters_file()]
    return {
        "items": filters,
        "total": len(filters),
        "source_file": str(content_filters_path()),
        "rules_file": str(spamassassin_filters_path()),
        "notes": [
            "Правила проверяют входящую почту через SpamAssassin внутри Amavis.",
            "При совпадении письмо получает высокий spam score и попадает в карантин (тип «Спам»).",
            "Поиск без учёта регистра, по вхождению указанного текста.",
            "Отправители из белого списка могут обходить проверку SpamAssassin.",
        ],
    }


def create_content_filter(field: str, pattern: str, enabled: bool = True) -> dict[str, Any]:
    filters = _read_filters_file()
    rule = _normalize_filter(
        {
            "id": secrets.token_hex(4),
            "field": field,
            "pattern": pattern,
            "enabled": enabled,
        }
    )
    filters.append(
        {
            "id": rule["id"],
            "field": rule["field"],
            "pattern": rule["pattern"],
            "enabled": rule["enabled"],
        }
    )
    _write_filters_file(filters)
    try:
        _apply_filters(filters)
    except Exception as exc:
        raise ContentFilterError(str(exc)) from exc
    return rule


def update_content_filter(
    rule_id: str,
    *,
    field: str | None = None,
    pattern: str | None = None,
    enabled: bool | None = None,
) -> dict[str, Any]:
    rule_id = _validate_rule_id(rule_id)
    filters = _read_filters_file()
    index = next((idx for idx, item in enumerate(filters) if str(item.get("id")) == rule_id), None)
    if index is None:
        raise ValueError(f"Правило не найдено: {rule_id}")

    current = dict(filters[index])
    if field is not None:
        current["field"] = _validate_field(field)
    if pattern is not None:
        current["pattern"] = _validate_pattern(pattern)
    if enabled is not None:
        current["enabled"] = bool(enabled)

    rule = _normalize_filter(current)
    filters[index] = {
        "id": rule["id"],
        "field": rule["field"],
        "pattern": rule["pattern"],
        "enabled": rule["enabled"],
    }
    _write_filters_file(filters)
    try:
        _apply_filters(filters)
    except Exception as exc:
        raise ContentFilterError(str(exc)) from exc
    return rule


def delete_content_filter(rule_id: str) -> None:
    rule_id = _validate_rule_id(rule_id)
    filters = _read_filters_file()
    next_filters = [item for item in filters if str(item.get("id")) != rule_id]
    if len(next_filters) == len(filters):
        raise ValueError(f"Правило не найдено: {rule_id}")
    _write_filters_file(next_filters)
    try:
        _apply_filters(next_filters)
    except Exception as exc:
        raise ContentFilterError(str(exc)) from exc
